(bind-key* "C-u" 'undo-tree-undo)
(bind-key* "M-u" 'undo-tree-redo)
(bind-key* "C-l" 'backward-char)
(bind-key* "M-l" 'backward-word)
(bind-key* "M-t" 'beginning-of-buffer)
(bind-key* "M-b" 'end-of-buffer)
(bind-key* "M-p" 'down-one)
(bind-key* "M-n" 'up-one)
(bind-key* "M-c" 'clipboard-kill-ring-save)
(bind-key* "C-;" 'dabbrev-expand)
(bind-key* "C-x C-k" 'kill-buffer)
;; (bind-key "C-xf" 'find-file)
(bind-key* "C-'" 'other-window)
;;(bind-key* "C-h" 'backward-delete-char)
(keyboard-translate ?\C-h ?\C-?)
(bind-key* "C-x f" 'helm-for-files)
(bind-key* "C-x C-f" 'find-file)
(bind-key* "M-y" 'helm-show-kill-ring)
(bind-key* "M-x" 'helm-M-x)
(bind-key* "C-c y" 'helm-c-yas-complete)
